### PR TITLE
Blame ehaas (name of branch for my new spider (fortheloveofcooking))

### PR DESCRIPTION
**Pull request by jterskine**
I created a new branch for adding my single spider (fortheloveofcooking), i'm hoping it doesn't combine everything, I made sure not to merge them. Please tell me if I screwd it up, thanks!

### CODE REVIEW

**Comment by funkatron** [comment]
Looks like this is everything, but that's fine. We'll work out a one-feature-per-branch situation next PR. I'll take this whole one and do testing.

**Comment by jterskine** [comment]
cool thanks. Sorry about that.

**Comment by funkatron** [comment]
Done. take a look at the commits I made https://github.com/fictivekin/openrecipes/commits/master

**Comment by jterskine** [comment]
Awesome, will check them soon when I get back. Thanks a lot! 
—

**Pull request merged**
